input PostInput {
  author: ID!
  title: String!
  content: String!
}

type Post {
  _id: ID!
  author: User!
  title: String!
  content: String!
}

type Query {
  posts: [Post!]!
  post(id: ID!): Post
}

type Mutation {
  createPost(data: PostInput!): Post!
  updatePost(id: ID!, data: PostInput!): Post!
  deletePost(id: ID!): Boolean!
}
